// heat.js — the Suspicion/Heat system (§17). Game-specific module.
// Heat is a tracked negative resource, not a currency: it is generated by uncancelled
// Despair in surveilled contexts, applies threshold effects, and decays slowly.
//
// The manual runs **one shared 0–5 track for the whole party** (§17). The older
// Personal + Cell split is kept as the printed optional variant (§17.5) behind
// `Settings.heatSplit()`. Everything below routes on that flag, so the rest of the app
// calls one set of functions whichever model is in force. In shared mode the single value
// is stored where the shared thing already lived — on the cell — and `personalHeat` is
// simply unused until the split is turned back on.

import { HEAT, BLACK_MARKET } from '../data.js';
import { clamp } from './core.js';
import { getCell, saveCell, saveCharacter } from './store.js';
import { Settings } from './settings.js';

export const EVASION_SKILLS = HEAT.generation.rules.find((r) => r.id === 'despairEvasion').skills;

/** Which of the two printed models is in force (§17 / §17.5). */
export const heatIsSplit = () => Settings.heatSplit();

/** The ladder to read: one column when shared, the two-column variant when split. */
export const heatThresholds = () => (heatIsSplit() ? HEAT.split.thresholds : HEAT.thresholds);

/** Heat generated by a resolved check (§17.1). Only surveilled contexts generate it.
 *  The returned `heat` is the delta for whichever track is in force; `personalHeat` is
 *  kept as an alias so older call sites read the same number. */
export function heatFromCheck({
  despair = 0, triumph = 0, surveilled = false, skillId = null, spendTriumphOnHeat = false,
  // House rule: a black-market deal that goes badly is as exposing as any public dealing,
  // so a failed check showing three threat counts as a surveilled context too.
  blackMarket = false, failed = false, threat = 0
} = {}) {
  const blackMarketExposure = blackMarket && failed
    && (threat >= BLACK_MARKET.heat.failedThreatThreshold || despair > 0);
  if (!surveilled && !blackMarketExposure) return { heat: 0, personalHeat: 0, reasons: [] };
  const label = heatIsSplit() ? 'Personal Heat' : 'Heat';
  const reasons = [];
  let delta = 0;
  if (despair > 0) {
    const evasion = skillId && EVASION_SKILLS.includes(skillId);
    const amount = evasion ? 2 : 1;
    delta += amount;
    reasons.push(evasion
      ? `Despair on an evasion check: ${label} +${amount}`
      : `Despair in a surveilled context: ${label} +${amount}`);
  }
  if (blackMarketExposure && despair === 0) {
    delta += 1;
    reasons.push('The deal went badly in public: suspicion +1 (house rule)');
  }
  if (triumph > 0 && spendTriumphOnHeat) {
    delta -= 1;
    reasons.push(`Triumph spent to reduce ${label} by 1`);
  }
  return { heat: delta, personalHeat: delta, reasons };
}

/** Threshold effects in force at a given level (§17.2). In shared mode there is one
 *  column, so both accessors read it. */
export function personalEffects(level) {
  return heatIsSplit()
    ? HEAT.split.thresholds.filter((t) => t.level <= level).map((t) => t.personal).filter(Boolean)
    : HEAT.thresholds.filter((t) => t.level <= level).map((t) => t.effect).filter(Boolean);
}

export function cellEffects(level) {
  return heatIsSplit()
    ? HEAT.split.thresholds.filter((t) => t.level <= level).map((t) => t.cell).filter(Boolean)
    : [];
}

/** Every effect in force right now, however the track is modelled. */
export function heatEffects({ personalHeat = 0, cellHeat = 0 } = {}) {
  return heatIsSplit()
    ? [...personalEffects(personalHeat), ...cellEffects(cellHeat)]
    : personalEffects(cellHeat);
}

/** Setback dice the current Heat adds to a public check (§17.2).
 *  Both the levels and the dice counts are read off the data — nothing is restated here. */
export function heatSetbackDice({ personalHeat = 0, cellHeat = 0, isPublicCheck = true }) {
  if (!isPublicCheck) return 0;
  if (!heatIsSplit()) {
    return HEAT.thresholds
      .filter((t) => t.level <= cellHeat && t.dice && t.dice.scope === 'public')
      .reduce((n, t) => n + (t.dice.setback || 0), 0);
  }
  const sum = (level, key) => HEAT.split.thresholds
    .filter((t) => t.level <= level && t[key] && t[key].scope === 'public')
    .reduce((n, t) => n + (t[key].setback || 0), 0);
  return sum(personalHeat, 'personalEffect') + sum(cellHeat, 'cellEffect');
}

/** The bestiary (B§) was written against the two-track model the manual has since replaced,
 *  and so were the two §12D hooks that cite it. With one shared track those names no longer
 *  refer to anything, so the printed wording is relabelled on its way to the screen rather
 *  than edited in the data files, which stay faithful to what is printed. */
export function heatWording(text) {
  if (heatIsSplit()) return text;
  return String(text)
    .replace(/Personal Heat and Cell Heat/g, 'suspicion')
    .replace(/Personal Heat/g, 'suspicion')
    .replace(/Cell Heat/g, 'suspicion');
}

/** How many moves a track remembers. Enough to answer "why am I at 3?" without becoming
 *  a second log. */
const HEAT_TRAIL_CAP = 12;

const pushTrail = (trail, before, after, reason) => [
  { ts: Date.now(), from: before, to: after, delta: after - before, reason: reason || 'Adjusted by hand' },
  ...(trail || [])
].slice(0, HEAT_TRAIL_CAP);

/** The current level, whichever model is in force. In shared mode a character is not
 *  needed at all — which is why a solo question with no sheet loaded can still raise it. */
export function currentHeat(character = null) {
  const cell = getCell();
  if (!heatIsSplit()) return { shared: cell.cellHeat || 0, cell: cell.cellHeat || 0, personal: null, split: false };
  return {
    shared: null, split: true,
    personal: character ? (character.state.personalHeat || 0) : 0,
    cell: cell.cellHeat || 0
  };
}

/** Move the track a check or a rule points at. In shared mode the character is only used
 *  to say **who** caused the rise (§17.4); the number itself is the party's. */
export function applyHeat(delta, { character = null, reason = null } = {}) {
  if (heatIsSplit()) {
    if (!character) return { ok: false, reason: 'No character is loaded to take the suspicion.' };
    return { ok: true, ...applyPersonalHeat(character, delta, reason) };
  }
  const who = character ? (character.identity.name || 'A character') : null;
  // §17.4 — the cost is shared; the fiction still names whose action caused it.
  const attributed = who && reason ? `${reason} (${who})` : reason;
  const moved = applyCellHeat(delta, attributed);
  return { ok: true, ...moved, crossed: crossedBetween(moved.before, moved.after), shared: true, attributedTo: who };
}

const crossedBetween = (before, after) =>
  heatThresholds().filter((t) => t.level > before && t.level <= after);

export function applyPersonalHeat(character, delta, reason = null) {
  // In shared mode there is no personal track; the call lands on the party's.
  if (!heatIsSplit()) return applyHeat(delta, { character, reason });
  const before = character.state.personalHeat || 0;
  const after = clamp(before + delta, HEAT.min, HEAT.max);
  character.state.personalHeat = after;
  // A reason trail, so the track can say how it got where it is (C-10).
  if (after !== before) character.state.heatTrail = pushTrail(character.state.heatTrail, before, after, reason);
  saveCharacter(character);
  const escalation = escalateCell(after);
  return { before, after, crossed: crossedBetween(before, after), escalation };
}

/** Any member at or past the escalation level pushes Cell Heat up (§17.5).
 *  Only meaningful in the split variant — with one track there is nothing to escalate to. */
export const CELL_ESCALATION_AT = HEAT.split.cellEscalationAtPersonal;

export function escalateCell(personalHeat) {
  if (!heatIsSplit()) return null;
  if (personalHeat < CELL_ESCALATION_AT) return null;
  const cell = getCell();
  const before = cell.cellHeat;
  cell.cellHeat = clamp(before + 1, HEAT.min, HEAT.max);
  cell.safehouseStatus = safehouseFor(cell.cellHeat);
  saveCell(cell);
  return { before, after: cell.cellHeat, reason: `A member reached Personal Heat ${CELL_ESCALATION_AT} or more` };
}

/** Safehouse status: the highest threshold at or below the level that names one (§17.2, §3.8). */
export function safehouseFor(cellHeat) {
  const reached = heatThresholds().filter((t) => t.level <= cellHeat && t.safehouseStatus);
  return reached.length ? reached[reached.length - 1].safehouseStatus : HEAT.safehouseDefault;
}

export function applyCellHeat(delta, reason = null) {
  const cell = getCell();
  const before = cell.cellHeat;
  cell.cellHeat = clamp(before + delta, HEAT.min, HEAT.max);
  cell.safehouseStatus = safehouseFor(cell.cellHeat);
  if (cell.cellHeat !== before) cell.heatTrail = pushTrail(cell.heatTrail, before, cell.cellHeat, reason);
  saveCell(cell);
  return { before, after: cell.cellHeat };
}

/** End-of-adventure resolution at maximum Heat (§24). Shared mode resolves the party's
 *  track; the split variant resolves the character's own. */
export function resolveMaxHeat(character, choice) {
  if (!heatIsSplit()) {
    const cell = getCell();
    if ((cell.cellHeat || 0) < HEAT.max) return null;
    if (choice === 'underground') {
      applyCellHeat(2 - cell.cellHeat, 'Went underground at the end of the adventure');
      return { outcome: 'underground', heat: 2, note: 'Relocated and disappeared; Heat resets to 2.' };
    }
    return { outcome: 'captured', note: 'Captured — the Oracle or GM decides whether they escape, turn, or leave play.' };
  }
  if ((character.state.personalHeat || 0) < HEAT.max) return null;
  if (choice === 'underground') {
    character.state.personalHeat = 2;
    saveCharacter(character);
    return { outcome: 'underground', personalHeat: 2, heat: 2, note: 'Relocated and disappeared; Heat resets to 2.' };
  }
  return { outcome: 'captured', note: 'Captured — the Oracle or GM decides whether they escape, turn, or leave play.' };
}
