// heat.js — the Suspicion/Heat system (§17). Game-specific module.
// Heat is a tracked negative resource, not a currency: it is generated by uncancelled
// Despair in surveilled contexts, applies threshold effects, and decays slowly.

import { HEAT } from '../data.js';
import { clamp } from './core.js';
import { getCell, saveCell, saveCharacter } from './store.js';

export const EVASION_SKILLS = HEAT.generation.rules.find((r) => r.id === 'despairEvasion').skills;

/** Heat generated by a resolved check (§17.1). Only surveilled contexts generate it. */
export function heatFromCheck({ despair = 0, triumph = 0, surveilled = false, skillId = null, spendTriumphOnHeat = false }) {
  if (!surveilled) return { personalHeat: 0, reasons: [] };
  const reasons = [];
  let delta = 0;
  if (despair > 0) {
    const evasion = skillId && EVASION_SKILLS.includes(skillId);
    const amount = evasion ? 2 : 1;
    delta += amount;
    reasons.push(evasion
      ? `Despair on an evasion check: Personal Heat +${amount} (§17.1)`
      : `Despair in a surveilled context: Personal Heat +${amount} (§17.1)`);
  }
  if (triumph > 0 && spendTriumphOnHeat) {
    delta -= 1;
    reasons.push('Triumph spent to reduce Personal Heat by 1 (§17.1)');
  }
  return { personalHeat: delta, reasons };
}

/** Threshold effects in force at a given level (§17.3). */
export function personalEffects(level) {
  return HEAT.thresholds.filter((t) => t.level <= level).map((t) => t.personal).filter(Boolean);
}

export function cellEffects(level) {
  return HEAT.thresholds.filter((t) => t.level <= level).map((t) => t.cell).filter(Boolean);
}

/** Setback dice the current Heat adds to a public check (§17.3). */
export function heatSetbackDice({ personalHeat = 0, cellHeat = 0, isPublicCheck = true }) {
  if (!isPublicCheck) return 0;
  return (personalHeat >= 1 ? 1 : 0) + (cellHeat >= 2 ? 1 : 0);
}

export function applyPersonalHeat(character, delta) {
  const before = character.state.personalHeat || 0;
  const after = clamp(before + delta, HEAT.min, HEAT.max);
  character.state.personalHeat = after;
  saveCharacter(character);
  const escalation = escalateCell(after);
  return { before, after, crossed: HEAT.thresholds.filter((t) => t.level > before && t.level <= after), escalation };
}

/** Any member at Personal Heat 3 or more pushes Cell Heat up (§17.2). */
export function escalateCell(personalHeat) {
  if (personalHeat < 3) return null;
  const cell = getCell();
  const before = cell.cellHeat;
  cell.cellHeat = clamp(before + 1, HEAT.min, HEAT.max);
  cell.safehouseStatus = safehouseFor(cell.cellHeat);
  saveCell(cell);
  return { before, after: cell.cellHeat, reason: 'A member reached Personal Heat 3 or more (§17.2)' };
}

export function safehouseFor(cellHeat) {
  if (cellHeat >= 5) return 'blown';
  if (cellHeat >= 3) return 'watched';
  return 'clear';
}

export function applyCellHeat(delta) {
  const cell = getCell();
  const before = cell.cellHeat;
  cell.cellHeat = clamp(before + delta, HEAT.min, HEAT.max);
  cell.safehouseStatus = safehouseFor(cell.cellHeat);
  saveCell(cell);
  return { before, after: cell.cellHeat };
}

/** End-of-adventure resolution for a PC sitting at maximum Heat (§24). */
export function resolveMaxHeat(character, choice) {
  if ((character.state.personalHeat || 0) < HEAT.max) return null;
  if (choice === 'underground') {
    character.state.personalHeat = 2;
    saveCharacter(character);
    return { outcome: 'underground', personalHeat: 2, note: 'Relocated and disappeared; Heat resets to 2 (§24).' };
  }
  return { outcome: 'captured', note: 'Captured — the Oracle or GM decides whether they escape, turn, or leave play (§24).' };
}
